kind: pipeline
type: docker
name: build
steps:
  - name: check
    image: node
    commands:
      - curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7 
      - pnpm install
      - pnpm svelte-check && pnpm build
trigger:
  branch:
  - master
---
kind: pipeline
type: docker
name: publish
  - name: publish
    image: node
    failure: "ignore"
    environment: 
      NPM_SECRET:
        from_secret: NPM_SECRET
    commands:
      - NPM_REGISTRY="//registry.npmjs.org/:_authToken="
      - echo "$NPM_REGISTRY$NPM_SECRET" > .npmrc
      - npm publish "router4svelte@$VERSION"

trigger:
  event:
  - promote
