kind: pipeline
type: docker
name: build
steps:
  - name: build_and_check
    image: node
    commands:
      - curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7 
      - pnpm install
      - pnpm svelte-check && pnpm build
trigger:
  branch:
  - master
---
kind: pipeline
type: docker
name: publish
steps: 
  - name: npm_publish
    image: node
    environment: 
      NPM_SECRET:
        from_secret: NPM_SECRET
    commands:
      - npm version "$DRONE_DEPLOY_TO"
      - NPM_REGISTRY="//registry.npmjs.org/:_authToken="
      - echo "$NPM_REGISTRY$NPM_SECRET" > .npmrc
      - npm publish

trigger:
  event:
  - promote
