kind: pipeline
type: docker
name: publish

steps:
- name: npm_publish
  image: node
  commands:
  - npm publish

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key: $GITEA_API_KEY
    base_url: $GITEA_BASE_URL
    files: 
      - dist
      - src

trigger:
  branch:
  - master
